<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="JsonTests.fs" />
    <Compile Include="SignetTests.fs" />
    <Compile Include="SpillwayTests.fs" />
    <Compile Include="SequencingProperties.fs" />
    <Compile Include="SiltTests.fs" />
    <Compile Include="OriginTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Undertow.Protocol/Undertow.Protocol.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Expecto" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
