<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Undertow.Protocol/Undertow.Protocol.fsproj" />
    <ProjectReference Include="../../src/Undertow.Storage.Memory/Undertow.Storage.Memory.csproj" />
    <ProjectReference Include="../../src/Undertow.Storage.Sqlite/Undertow.Storage.Sqlite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
